# Generated by Django 3.0.6 on 2020-06-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_temp', models.FloatField(blank='null')),
                ('min_temp', models.FloatField(blank='null')),
                ('max_temp', models.FloatField(blank='null')),
                ('rain_fall', models.FloatField(blank='null')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank='null', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Plantsub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField(blank='null')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Plantimage')),
            ],
        ),
    ]
