# Generated by Django 3.0.6 on 2020-06-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank='null', upload_to='')),
                ('device', models.TextField(blank='null')),
                ('date', models.TextField(blank='null')),
                ('first_name', models.CharField(blank='null', max_length=30)),
                ('first_percent', models.FloatField(blank='null')),
                ('second_name', models.CharField(blank='null', max_length=30)),
                ('second_percent', models.FloatField(blank='null')),
            ],
        ),
        migrations.CreateModel(
            name='Plantadd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.TextField(blank='null')),
                ('name', models.CharField(blank='null', max_length=30)),
                ('flower', models.TextField(blank='null')),
                ('content', models.TextField(blank='null')),
                ('image', models.TextField(blank='null')),
            ],
        ),
        migrations.CreateModel(
            name='Plantconnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='null', max_length=30)),
                ('flower', models.TextField(blank='null')),
                ('content', models.TextField(blank='null')),
                ('image', models.FileField(blank='null', upload_to='')),
            ],
        ),
    ]
