# Generated by Django 3.0.6 on 2020-06-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.TextField(blank='null'),
        ),
        migrations.AddField(
            model_name='test',
            name='device',
            field=models.TextField(blank='null'),
        ),
    ]
